### Introduction to Natural Language Processing

In [1]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
# Corpus - A large collection of text
from nltk.corpus import brown

In [4]:
print(brown.categories())
print(len(brown.categories()))

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [5]:
data = brown.sents(categories= 'adventure')

In [6]:
" ".join(data[0])

'Dan Morgan told himself he would forget Ann Turner .'

### Bag of Words Pipeline
- Get the Data/Corpus
- Tokenisation, Stopword Removal
- Stemming
- Building a Vocab
- Vectorization
- Classification

### Tokenization & Stopword Removal

In [7]:
from nltk.tokenize import sent_tokenize, word_tokenize

In [8]:
document = """It was a very pleasent day. 
The weather was cool and there were light showers. 
I went to the market to buy some fruits."""

sentence = "Send all the 50 document related to chpaters 1,2,3 at prateek@cb.com"


In [9]:
sents = sent_tokenize(document)
print(sents)

['It was a very pleasent day.', 'The weather was cool and there were light showers.', 'I went to the market to buy some fruits.']


In [10]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'document',
 'related',
 'to',
 'chpaters',
 '1,2,3',
 'at',
 'prateek@cb.com']

In [11]:
words = word_tokenize(sentence)

In [12]:
words

['Send',
 'all',
 'the',
 '50',
 'document',
 'related',
 'to',
 'chpaters',
 '1,2,3',
 'at',
 'prateek',
 '@',
 'cb.com']

### Stopwords

In [13]:
from nltk.corpus import stopwords

sw = set(stopwords.words('english'))

In [14]:
def remove_stopwords(text, stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [15]:
text = "I am not bothered about her very much".split()
useful_text = remove_stopwords(text, sw)
print(useful_text)

['I', 'bothered', 'much']


### Tokenization using Regualar Expression

In [16]:
from nltk.tokenize import RegexpTokenizer

In [17]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful_text = tokenizer.tokenize(sentence)

In [18]:
useful_text

['Send',
 'all',
 'the',
 'document',
 'related',
 'to',
 'chpaters',
 'at',
 'prateek@cb.com']

### Stemming
- Process that transform particular words(verbs, plurals) into their radical form
- Preserve the semantics of the sentence without increasing the number of unique tokens
- Example - jumps, jumping , jumped, jump ==> jump

In [19]:
text = """Foxex love to make jumps. 
The quick brown fox was seen jumping 
over the lovely dog from a 6ft high wall"""

In [20]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [21]:
ps = PorterStemmer()

In [22]:
ps.stem('jumping')

'jump'

In [23]:
ss = SnowballStemmer('english')

In [24]:
ss.stem('jumping')

'jump'

In [25]:
## Lematization
from nltk.stem import WordNetLemmatizer

In [26]:
wn = WordNetLemmatizer()
wn.lemmatize('jumping')

'jumping'

### Building a Vocab & Vectorization

In [27]:
corpus = [
    'Indian cricket team will wins World Cup, says Capt. Virat kohli. World cup will be held at Sri Lanka',
    'We will win next Lok Sabha Elections, says confident Indian PM',
    'The nobel laurate won the hearts of the people.',
    'THe movie Raazi is an exciting Indian Spy thriller based upon a real story.'
]

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv = CountVectorizer()

In [30]:
vectorized_corpus = cv.fit_transform(corpus)

In [32]:
vectorized_corpus = vectorized_corpus.toarray()

In [35]:
print(cv.vocabulary_)

{'indian': 12, 'cricket': 6, 'team': 31, 'will': 37, 'wins': 39, 'world': 41, 'cup': 7, 'says': 27, 'capt': 4, 'virat': 35, 'kohli': 14, 'be': 3, 'held': 11, 'at': 1, 'sri': 29, 'lanka': 15, 'we': 36, 'win': 38, 'next': 19, 'lok': 17, 'sabha': 26, 'elections': 8, 'confident': 5, 'pm': 23, 'the': 32, 'nobel': 20, 'laurate': 16, 'won': 40, 'hearts': 10, 'of': 21, 'people': 22, 'movie': 18, 'raazi': 24, 'is': 13, 'an': 0, 'exciting': 9, 'spy': 28, 'thriller': 33, 'based': 2, 'upon': 34, 'real': 25, 'story': 30}


In [36]:
len(vectorized_corpus[0])

42

In [37]:
len(cv.vocabulary_.keys())

42

In [50]:
# Reverse Mapping!
numbers = vectorized_corpus[2]
numbers

numpy.ndarray

In [52]:
s = cv.inverse_transform(numbers.reshape(1, -1))
print(s)

[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
      dtype='<U9')]


### Vectorization with Stopword Removal

In [53]:
def myTokenizer(document):
    words = tokenizer.tokenize(document.lower())
    # Remove Stopwords
    words = remove_stopwords(words, sw)
    return words

In [55]:
myTokenizer(sentence)

['send', 'document', 'related', 'chpaters', 'prateek@cb.com']

In [56]:
cv = CountVectorizer(tokenizer=myTokenizer)

In [57]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [58]:
vectorized_corpus

array([[0, 1, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
        0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0]], dtype=int64)

In [60]:
len(vectorized_corpus[0])

33

In [61]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.', 'cricket', 'cup', 'held', 'indian', 'kohli.', 'lanka',
        'says', 'sri', 'team', 'virat', 'wins', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurate', 'nobel', 'people.'], dtype='<U9'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U9')]

In [62]:
# For Test Data
test_corpus = [
    'Indian cricket rock!'
]

In [63]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### More ways to Create Features
- Unigram - every word as a feature
- Bigrams
- Trigrams
- n-grams
- TF-IDF Normalisation

In [67]:
sent_1 = ["this is good movie"]
sent_2 = ["this is good movie but actor is not present"]
sent_3 = ["this is not good movie"]

In [74]:
cv = CountVectorizer(ngram_range= (1, 3))

In [75]:
docs = [sent_1[0], sent_2[0], sent_3[0]]
cv.fit_transform(docs).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 1]], dtype=int64)

In [76]:
cv.vocabulary_

{'this': 23,
 'is': 9,
 'good': 6,
 'movie': 15,
 'this is': 24,
 'is good': 10,
 'good movie': 7,
 'this is good': 25,
 'is good movie': 11,
 'but': 3,
 'actor': 0,
 'not': 18,
 'present': 22,
 'movie but': 16,
 'but actor': 4,
 'actor is': 1,
 'is not': 12,
 'not present': 21,
 'good movie but': 8,
 'movie but actor': 17,
 'but actor is': 5,
 'actor is not': 2,
 'is not present': 14,
 'not good': 19,
 'this is not': 26,
 'is not good': 13,
 'not good movie': 20}

### Tf-idf Normalisation
- Avoid features that occur very often, because they contain less information
- Information decreases as the number of occurences increases across different type of documents
- So we define another term - term - document - frequecy which associates a weight with every term

In [77]:
sent_1 = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not good movie"

corpus = [sent_1, sent_2, sent_3]

In [78]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [79]:
tfidf = TfidfVectorizer()

In [80]:
vc = tfidf.fit_transform(corpus).toarray()

In [81]:
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [82]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}