In [1]:
import numpy as np

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print(np.min(a))

# Specify axis for the direction in case of multidim array
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))




[[1 2 3 4]
 [5 6 7 8]]
1
[1 2 3 4]
[1 5]


In [6]:
# Mean, average all the elements
b = np.array([1, 2, 3, 4, 5])
m = sum(b) / 5

print(np.mean(b))

3.0


In [8]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

# Mean vs Average is weighted
print(np.mean(c))

w = np.array([1, 2, 3, 4, 5])

print(np.average(c, weights=w))

2.0
2.4
2.066666666666667


In [9]:
# Standard Deviation
u = np.mean(c)
myStd  = np.sqrt(np.mean(abs(c - u) ** 2))
print(myStd)

dev = np.std(c)
print(dev)

1.854723699099141
1.854723699099141


In [10]:
# variance
print(myStd ** 2)
print(np.var(c))

3.440000000000001
3.4400000000000004
