In [1]:
import numpy as np

In [2]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[6 8 9]


In [15]:
# Returns values from a standard normal distributuion
a = np.random.rand(2, 3)
print(a)

a = np.random.randint(5, 10, 3)
print(a)

# Randomly pick one element from an array
element = np.random.choice([1, 2, 3, 4, 7, 11, 27])
print(element)

[[0.8781425  0.09834683 0.42110763]
 [0.95788953 0.53316528 0.69187711]]
[6 8 9]
3
